# fly.toml app configuration file generated for meetingapp on 2024-08-06T16:56:36+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meetingapp'
primary_region = 'jnb'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
